// <auto-generated />
using System;
using Books.MinimalApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Books.MinimalApi.Contexts.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20220603171834_SeedDummyData")]
    partial class SeedDummyData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Books.MinimalApi.Entities.BookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("53e5d3e2-3301-4875-af1d-2193dd3879fc"),
                            Name = "C# In Nutshell",
                            Pages = 900,
                            Price = 35.0
                        },
                        new
                        {
                            Id = new Guid("277e4596-d86b-4833-81d4-beef245fb637"),
                            Name = "JAVA",
                            Pages = 620,
                            Price = 23.0
                        },
                        new
                        {
                            Id = new Guid("bce11a1b-daec-47ad-9163-ef810a789ba8"),
                            Name = "How to make Hawawshi?",
                            Pages = 66,
                            Price = 8.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
